### ISSUE TITLE
Testing CCB-268

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/pds4-information-model#143]
https://pds-jira.jpl.nasa.gov/browse/CCB-268 has no examples, so I:
1) added a <Terminological_Entry> to a DD_Attribute in an LDD input file
2) set Terminological_Entry/skos_relation_name to a legal value like broadMatch
So this validates, but lddtool does nothing with skos_relation_name

Or am I supposed to directly edit a Product_Attribute_Definition? That would validate, but again I don't see how that can "provide more than one descriptor for instruments that are functionally very much the same but not identical."

**Comment by jshughes** [comment]
> So this validates, but lddtool does nothing with skos_relation_name

This is correct. The purpose of skos_relation_name is to provide additional information about aliases, namely how 'close" the aliases are in meaning to the preferred name. This information can be used by PDS4 software and services to inform users and guide search, for example. It is also useful to data providers when deciding on the terms to use when preparing data products for ingesting. Attached is an early version of how skos_relation_name could be used to relate aliases to the preferred values of instrument.type.


[input_IngestLDDTool_TypeList_1E00.txt](https://github.com/NASA-PDS-Incubator/pds4-information-model/files/4327469/input_IngestLDDTool_TypeList_1E00.txt)

**Comment by rchenatjpl** [comment]
@jshughes What rules were (are) contradictory?  The 5 infomodel links after "Delete the following entries in the Protege database:" are all 404 for me. I don't even know if those would help, but nothing else does. Ideally, this github page would say, "line xxx in PDS4_DISP_1H00_1510.sch contradicted line yyy in PDS4_PDS_1H00.sch".

**Comment by jshughes** [comment]
@rchenatjpl This is a tricky one and I can only tell you what I removed. 

The rules that were causing the problem were defined in the common model however they were never written to the pds schematron file. They were only written to the disp: schematron file during LDDTool process of the disp Ingest_LDD file. The problem was that the disp: Ingest_LDD  also defined similar rules, causing the contradictions since both sets were written to the disp: schematron file. I do not have the line numbers for the offending lines in the schematron file but the three assert statements removed from the common pds: model were the following. These rules were in IM V 1G00. They are not in IM V1H00.

xpath: "disp:Discipline_Area"
assert: if (disp:Display_Direction) then (disp:Display_Settings/disp:Display_Direction) else true()

xpath: "disp:Display_Settings/pds:Local_Internal_Reference"
assert: pds:local_identifier_reference = //pds:*/pds:*/(pds:Array|pds:Array_2D|pds:Array_2D_Image|pds:Array_2D_Map|pds:Array_2D_Spectrum|pds:Array_3D|pds:Array_3D_Image|pds:Array_3D_Movie|pds:Array_3D_Spectrum)/pds:local_identifier

assert: pds:local_reference_type = ('display_settings_to_array')

As to why the disp: rules were in the Common model in the first place, at one time we planned on merging all LDDs into one database. Luckily we changed our minds but the disp: dictionary had been merged in as a test case.

Also, I do not know how this issue got associated with CCB 268. They are not related.

I hope this helps,
Steve

**Comment by jordanpadams** [comment]
@rchenatjpl @jshughes what are we doing with this? can we close this or is this still an issue?

**Comment by rchenatjpl** [comment]
I'm closing this. My best understanding of this issue is that PDS4_PDS_*.sch at one time may have had some rules about Display_Settings that collided with the Display dictionary, but the only possible collision point in PDS4_PDS_1J00.sch are rules about pds:Display_2D_Image, which 1) I've never seen used, and 2) always triggers a deprecated warning.
