### ISSUE TITLE
DPH example package contains invalid label

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds4-information-model#272]
**Describe the bug**
On https://pds.nasa.gov/datastandards/documents/examples/
version 1.14
The file dph_example_products/Product_Observational/Table_Character_draft1.xml file.
The file has empty lid and vid fields:

<logical_identifier/>
<version_id/>

The file can be removed or filled with valid values.

The bug was identified in https://github.com/NASA-PDS/pds-registry-app/issues/109

**Comment by jordanpadams** [comment]
@sslavney see bug identified in the DPH example products. can we jot this down for the next IM update? or do we need an SCR for this?

**Comment by sslavney** [comment]
I don't think that should count as a bug. It's a draft label that is deliberately incomplete, and it is used in the DPH as part of an example for how to fill in a label. However, there _are_ issues with the DPH examples that have prevented me from updating them for IM 1F00. Some of the examples use the "sp" local data dictionary, which has changed a lot since the examples were created, and I don't know how (and have not had time to figure out how) to revise them. It's on my list, but not high priority.

**Comment by jordanpadams** [comment]
@sslavney thanks Susie. We will just ignore this issue then.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl FYI, closed this as wontfix. See comments above
