### ISSUE TITLE
Tag ops classes/attributes in IM so they are easily identifiable by users

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#281]
**Is your feature request related to a problem? Please describe.**
From Joe M. at PPI:

>     I see that the look of the PDS4 Data Dictionary has been updated on the
>     EN website. In the new-look version I see that the ops stewarded product
>     classes are listed alongside the pds stewarded ones. Was this the case
>     in the previous implementation, it may be that I was just so used to it
>     that I ignored the ops classes? Is there something we can do to more
>     clearly distinguish the ops products from the pds one's? It may prevent
>     us from having some well meaning data provider submit a bunch of
>     products labeled as Product_Software, or some other non-archival product
>     type

**Describe the solution you'd like**
@jshughes will discuss this with DDWG about adding some "tag" or explicit description to the ops classes/attributes so these can be separated out in the DD search / Information Specification.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams this ticket is closed but I am not sure if it should be tested by I&T and if yes, how so ? Thanks

**Comment by jordanpadams** [comment]
@tloubrieu-jpl I have no idea :-) . @jshughes is there some way the I&T team can generate the appropriate documentation to test this?

**Comment by jshughes** [comment]
@jordanpadams @jordanpadams The request was to reorganize the PDS4 Data Dictionary so that the “ops” stewarded items in the common “pds” namespace were more “easily” identified. Prior to this change these items could identified by the label “Steward: ops” in the item’s description. 
Since no guidance was provided, the solution chosen was to group all “ops” stewarded items into one section in the document. This was easily accomplished since the ”PDS3 catalog classes” section already included a subset of the “ops” items. To resolve the issue, the ”PDS3 catalog classes”  section was renamed to “OPS catalog classes in the common namespace” and all “ops” items were moved to the renamed section. 
To test this change, the tester should check if the “OPS catalog” section contains only “ops” classes. A more extensive test would check to see if any “ops” classes existed outside of the “OPS catalog” section.

**Comment by jordanpadams** [comment]
@jshughes that sounds great. Do we have docs somewhere so the I&T team can actually generate and see these docs to verify this works? If not, don't worry about that right now. We can add that as a task for next build.
