### ISSUE TITLE
[namespace-registry] update path "<clementine>" in registry PDF (possibly shorten name)

### ISSUE THREAD

**Issue by thareUSGS** [NASA-PDS/pds4-information-model#373]
A couple questions (maybe issues).

reference:  https://pds.nasa.gov/datastandards/dictionaries/pds-namespace-registry.pdf

1. I noticed the to "clementine" in this document is missing "mission"
http://pds.nasa.gov/pds4/clementine/v1
should be http://pds.nasa.gov/pds4/mission/clementine/v1

2. The Schema filename prefix is PDS4_clementine but following others should it be PDS4_CLEMENTINE ?

3. When I submitted I didn't think about how almost "every" other mission is abbreviated. Thus, should this be "clem"? If we are going to change it, now is the time. If we do then other fields in table will need to updated.  the long name doesn't bother me, just trying to keep it consistent.

thanks.

**Comment by jshughes** [comment]
1) Yes, http://pds.nasa.gov/pds4/mission/clementine/v1 is correct and the update has been made. However this change does not affect operations since LDDTool creates the namespace. This document is primarily used as documentation.
2) Yes, PDS4_CLEMENTINE is correct and the update has been made. Again, this change will not affect operations.
3) Yes, most other mission namespace ids are shorter. However PSA has many long names for their instrument LDDs.
Your call on making the change.

**Comment by thareUSGS** [comment]
I am fine with the long name. I will close this.
