### ISSUE TITLE
Different formatting of JSON output between 1F00 and 1G00 generation

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#397]
## 🐛 Describe the bug

In [PDS4_SPECLIB_1G00_1100.JSON](https://pds.nasa.gov/pds4/speclib/v1/PDS4_SPECLIB_1G00_1100.JSON) new class definitions were introduced in "dataDictionary": { "classDictionary": section.
These new definitions use nested / XPath-like class IDs, similar to this (**0001_NASA_PDS_1.speclib.Ancillary_Product.pds.Internal_Reference**):
 
```
          "class": {
            "identifier": "0001_NASA_PDS_1.speclib.Ancillary_Product.pds.Internal_Reference" ,
            "title": "Ancillary_Product_Internal_Reference" ,
            "registrationAuthorityId": "0001_NASA_PDS_1" ,
            "nameSpaceId": "speclib" ,
            "steward": "geo" ,
            "versionId": "1.0.0.0" ,
            "isAbstract": "false" ,
            "isDeprecated": "false" ,
```
 
New definition has 2 nested classes in the ID: (1) `speclib.Ancillary_Product` and (2) `pds.Internal_Reference` combined together.

Also, those 2 classes have different namespaces.
 
Before we never had IDs like that. The algorithm in Registry Manager (1) could not work with nested classes. It only understands IDs like
```
          "class": {
            "identifier": "0001_NASA_PDS_1.speclib.Ancillary_Product" ,
```
 
(2) only works with one namespace at a time.
 
Previous version, [PDS4_SPECLIB_1F00_1100.JSON](https://pds.nasa.gov/pds4/speclib/v1/PDS4_SPECLIB_1F00_1100.JSON), does not have any nested class IDs and can be loaded into registry.

(as described by @tdddblog)

## 🕵️ Expected behavior

The output should be the same, or we should understand why it is different and update registry manager accordingly.

## 📚 Version of Software Used

LDDTool v13.0.2

## 🩺 Test Data / Additional context

https://pds.nasa.gov/pds4/speclib/v1/PDS4_SPECLIB_1G00_1100.JSON
https://pds.nasa.gov/pds4/speclib/v1/PDS4_SPECLIB_1F00_1100.JSON

---

**Comment by jshughes** [comment]
The concern is that the Association  identifier 0001_NASA_PDS_1.speclib.Ancillary_Product.pds.Internal_Reference has changed between V1F00 and V1G00. This is true but only in the case where the new DD_Associate_External_Class is being used. The developer of the LDD speclib chose to use DD_Associate_External_Class for V1G00.

The use of DD_Associate_External_Class allows a single class external to the local namespace, e.g., pds.Internal_Reference, to be referenced from any local class, e.g., speclib.Ancillary_Product. This means that each resulting Association must be uniquely identified, e.g., 0001_NASA_PDS_1.speclib.Ancillary_Product.pds.Internal_Reference, or otherwise there would be identifier collisions for the Associations.
		   
However the identifier of the referenced Class remains the same e.g., 0001_NASA_PDS_1.pds.Internal_Reference, as shown in the actual class reference list, namely the <classId> list at the end of the Association definition. This means that the identifier of the reference class has not changed. Only the identifier of the Association has changed.

           , {"association": {
                "identifier": "0001_NASA_PDS_1.speclib.Ancillary_Product.pds.Internal_Reference" ,
                "title": "Internal_Reference" ,
                "assocType": "component_of" ,
                "isAttribute": "false" ,
                "isChoice": "false" ,
                "isAny": "false" ,
                "groupName": "null" ,
                "minimumCardinality": "1" ,
                "maximumCardinality": "1" ,
                "classOrder": "1010" ,
                "classId": [
                  "0001_NASA_PDS_1.pds.Internal_Reference"
                 ]
              }
            }

**Comment by jordanpadams** [comment]
closing per https://github.com/NASA-PDS/pds4-information-model/issues/397#issuecomment-908595191 as wontfix

**Comment by rchenatjpl** [comment]
@jshughes @jordanpadams Sorry, what is lddtool supposed to do now - remove or leave the nested class? I ran the latest lddtool on PDS4_SPECLIB_IngestLDD.xml and got no nested class in the .JSON. Is that what's supposed to happen?

**Comment by jordanpadams** [comment]
@rchenatjpl this was closed as wontfix/invalid so does not need to be tested
