### ISSUE TITLE
schematron reports senseless WARNING with sensible ERROR

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/pds4-information-model#413]
The .sch throws a correct ERROR and an incorrect WARNING when an Internal_Reference has a lid_reference but not a reference_type. Ignoring this "is_airborne" bug may be ok because 1) clearing the ERROR should clear the warning, and 2) fixing this might break whatever the solution was to CCB-245. This came up when I was testing pds4-information-model#324 (inherit a class/attribute defined using DD_Associate_External_Class), though the attachment shows that this bug arises even for labels that have no LDD.

% validate -x PDS4_PDS_1H00.xsd -S PDS4_PDS_1H00.sch -t ../SEDR_HG.xml
PDS Validate Tool Report
Configuration:
   Version                       2.2.0-SNAPSHOT
   Date                          2021-10-14T03:26:01Z
Parameters:
   Targets                       file:/Users/rchen/Desktop/SEDR_HG.xml
   User Specified Schemas        file:/Users/rchen/Desktop/im/PDS4_PDS_1H00.xsd
   User Specified Schematrons    file:/Users/rchen/Desktop/im/PDS4_PDS_1H00.sch
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  FAIL: file:/Users/rchen/Desktop/SEDR_HG.xml
      ERROR  [error.label.schema]   line 49, 29: cvc-complex-type.2.4.b: The content of element 'Internal_Reference' is not complete. One of '{"http://pds.nasa.gov/pds4/pds/v1":reference_type}' is expected.
      WARNING  [warning.label.schematron]   line 49, 29: The value is_airborne for attribute Internal_Reference.reference_type is deprecated and should not be used.
        1 product validation(s) completed
Summary:
  1 error(s)
  1 warning(s)
  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped
  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped
  Message Types:
    1            error.label.schema
    1            warning.label.schematron
End of Report
Completed execution in 2705 ms

[CCB-341.zip](https://github.com/NASA-PDS/pds4-information-model/files/7436469/CCB-341.zip)

**Comment by jshughes** [comment]
Current analysis suggests that the triggered Error condition, caused by a required but missing attribute <reference_type>, also triggers a bogus Warning. This Warning seems to be triggered by the first of many rules that check for deprecated values(s) of <reference_type>. This Warning is a nuisance but disappears once the Error is fixed. One possible fix would be to rewrite all of the value "deprecation" rules. But this would also be a nuisance.

**Comment by jshughes** [comment]
Closed due to the fact that the negative impact of the change to remove the bogus warning is not worth the benefit. The change would require rewriting the many schematron rules that validate <reference_type>. This in turn would impact the validation process itself, requiring more time to process more complex rules. Finally, the error that causes the warning is seldom encountered. It is a simple syntax error caused by omitting a required XML tag/attribute.
