### ISSUE TITLE
LDDTool is not combining Schematron Contexts correctly when adding to an auto-generated context

### ISSUE THREAD

**Issue by acraugh** [NASA-PDS/pds4-information-model#459]
## 🐛 Describe the bug
LDDTool automatically generates Schematron rules with the appropriate contexts to enforce constraints like units of measure and permissible value lists. LDDTool also successfully combines rules defined in separate <DD_Rule> statements that specify the same value for <rule_context>. But, if a <DD_Rule> defines a new rule for a <rule_context> that is the same as the context for an automatically generated rule, the rules are not combined into the same context in the output Schematron file. Instead the context will be repeated in the Schematron file.  The Schematron standard states that in this case, which context is executed is implementation-dependent.

Currently, Validate tool processes rules in both context areas.

## 📜 To Reproduce
Kiri Wagstaff uploaded a sample set to reproduce the error in the DMSP workspace.

## 🕵️ Expected behavior
Contexts should be unique to avoid differences in validation behavior as underlying libraries evolve, so automatically generated rules should be combined with steward-defined rules when contexts coincide.

## 📚 Version of Software Used
Unknown, but this aspect of LDDTool behavior has been stable for many releases.

---

**Comment by jshughes** [comment]
A bug was found where a schematron rule from an Ingest_LDD file was being written separately instead of being combined with an existing (common) schematron rule for Units of Measure. The bug has been fixed. Before and after files are attached. 

The fix consists of merging the assert statement

      <sch:assert test="@unit = 'arcsec'">
        <title>rule_units_rollover_fwhm/Rule</title>
        The rollover_fwhm must have unit = 'arcsec'.</sch:assert>

 into the following rule.

  <sch:pattern>
    <sch:rule context="survey:Rollover/survey:rollover_fwhm">
      <sch:assert test="@unit = 'arcsec'">
        <title>rule_units_rollover_fwhm/Rule</title>
        The rollover_fwhm must have unit = 'arcsec'.</sch:assert>
      <sch:assert test="@unit = ('arcmin', 'arcsec', 'deg', 'hr', 'mrad', 'rad')">
        <title>survey:Rollover/survey:rollover_fwhm/survey:rollover_fwhm</title>
        The attribute @unit must be equal to one of the following values 'arcmin', 'arcsec', 'deg', 'hr', 'mrad', 'rad'.</sch:assert>
    </sch:rule>
  </sch:pattern>
[PDS4_PDS_1I00.sch.txt](https://github.com/NASA-PDS/pds4-information-model/files/8585943/PDS4_PDS_1I00.sch.txt)

[PDS4_PDS_1I00_error.sch.txt](https://github.com/NASA-PDS/pds4-information-model/files/8585944/PDS4_PDS_1I00_error.sch.txt)

**Comment by jordanpadams** [comment]
@jshughes so is this something that needs to be done in LDDTool? Or is this fixed? Or is this a documentation thing?
