### ISSUE TITLE
LDDTool is generating multiple Schematron rules to test the same condition

### ISSUE THREAD

**Issue by acraugh** [NASA-PDS/pds4-information-model#468]
## 🐛 Describe the bug
There is a class in the Display namespace called Movie_Dsiplay_Settings that contains two attributes that are defined as boolean values. LDDTool is automaticall generating individual test for each attribute (at line 67 and 81 in the attached Schematron), in addition to two duplicate tests executed at the class level (line 50 and following in the attached Schematron).

## 📜 To Reproduce
The attached IngestLDD source file was uploaded to the dmsp-test branch of the current repo to produce the attached output XSD and SCH files. There is no rule for either context explicitly defined in the IngestLDD.

[display_demo.zip](https://github.com/NASA-PDS/pds4-information-model/files/8556172/display_demo.zip)

## 🕵️ Expected behavior
Only one set of tests should be generated. Either would do.

## 📚 Version of Software Used
However the CI bot was configured on 21 April 2022, when the IngestLDD was last changed.

## 🩺 Test Data / Additional context
The attached zip file contains the IngestLDD and output XSD and SCH from the ldd-disp repo.

##  🏞Screenshots
N/A

## 🖥 System Info
N/A
---

**Comment by thareUSGS** [comment]
Per @jordanpadams, LDDTool should be updated to not add additional tests and we can rely on the IngestLDD.

To be clear, to solve this, I don't plan on updating anything in the DISP ingest file.

**Comment by acraugh** [comment]
@thareUSGS and @jordanpadams: that is correct; there seems to be no action required by the steward (or DMSP team, come to that). Multiple boolean attributes in one class is probably a rare occurrence, but it is clearly nothing done explicitly in the IngestLDD file causing it. If the same thing happens to be noted in other namespaces, we can simply refer to this issue. We've already determined that, at least with respect to the PDS4 tools, no harm is being done by the extra tests - just a few wasted CPU cycles.

**Comment by jordanpadams** [comment]
thanks @acraugh @thareUSGS we will take a look. should be a pretty straightforward fix, but if not, we will skip it.

**Comment by tloubrieu-jpl** [comment]
@gxtchen @jpl-jengelke this need to be tested on the latest snapshot version https://github.com/NASA-PDS/pds4-information-model/releases/tag/v14.1.0-SNAPSHOT

**Comment by rchenatjpl** [comment]
@jpl-jengelke or anyone with an opinion: to test this, I'd feed the lddinput.xml file into lddtool, then create a label that incorrectly uses either (or both) of the attributes in question (e.g. set the value to "maybe") and see if only 1 validate error message pops up. For your own curiosity, you could feed the same lddinput.xml file into an old version of lddtool and then validate against it, but I somehow don't like including old versions into the formal test doc. I forget why I have that bias.

**Comment by jshughes** [comment]
> clearly nothing done explicitly in the IngestLDD file causing it.

Actually, the specification of the permissible values “true” and “false” for an attribute with type ASCII_Boolean was part of the problem. 

The use of the attribute type ASCII_Boolean by definition will test for the values of “true” and “false”.  But LDDTool also auto-generates tests for user defined permissible values. 

So, instead of suggesting a change to the Ingest_LDD file to fix the “problem”, it was assumed that re-defining the permissible values was a type of implicit extension of the type ASCII_Boolean to provide more specific value meanings, e.g. “true - When looping, the movie should be played in the forward direction, followed by the reverse direction, iteratively.”

From one perspective, schematron rules for the user defined permissible values are reasonable, even if they are duplicate tests. In any case the code was changed to not generate rules for user defined permissible values of an attribute with type ASCII_Boolean.
