### ISSUE TITLE
Rings Ontology: Complete 1st draft for distribution

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#774]
### 💡 Description

Create first draft and submit to RMS for review.

**Comment by jordanpadams** [comment]
Status: Submitted to RMS for review. Awaiting feedback.

**Comment by matthewtiscareno** [comment]
@mit3ch and I have looked at this and will schedule a time to meet with Sara.

**Comment by jordanpadams** [comment]
Status: Plans to tag-up and discuss a bit more in the next few weeks

**Comment by jordanpadams** [comment]
📆 Status: Continuing to work on getting Protege installed and getting information documented appropriately, but blocked by some technical issues. Looking to make some progress in the next 2 weeks.

**Comment by sarabond** [comment]
Provided examples of ontology work with screenshots:

![Screenshot 2024-09-13 at 4 37 01 PM](https://github.com/user-attachments/assets/c921ec9b-87e7-42e6-99c9-d8808793e109)
![Screenshot 2024-09-13 at 4 26 46 PM](https://github.com/user-attachments/assets/3e514dfa-4714-46e4-8e50-5663e602e5f4)

**Comment by matthewtiscareno** [comment]
There is a lot to like in what you’re doing here, @sarabond.  Here are some questions and comments:

Firstly, what source are you using for these parameters? The Huygens Ringlet is eccentric and also has higher-order irregularities in its edges.  I’m not sure whether the inner and outer boundaries are consistently [117806,117824] km.  In fact, Table 13.2 of Colwell et al. (2009, Saturn book) lists the edges as [117815,117834] while also noting its non-circularity.

**Comment by matthewtiscareno** [comment]
Secondly, the Huygens Ringlet is within the Cassini Division, which I think might be best defined as a region of Saturn’s rings.  This might be an intermediate level for you to consider.  Radially outward, the “regions” of Saturn’s ring system are 
> D Ring
> C Ring
> B Ring
> Cassini Division
> A Ring
> Roche Division
> F Ring
> G Ring
> E Ring

We could supply radial distances as boundaries for these regions.

**Comment by matthewtiscareno** [comment]
Thirdly, the Alpha ring definition might need to be scrubbed, since it would need to be modified if a ring were to be discovered inward of it, thus making it no longer the "fifth."

**Comment by matthewtiscareno** [comment]
Finally, I notice that the attributes are listed in alphabetical order rather than logical order.  For example, it would make sense for `DistanceType` to be immediately followed by `MiddleBoundaryDist` and then by `Width`.  But that's only an issue of human readability, and I'm not sure how important that is to your project.

**Comment by matthewtiscareno** [comment]
Will you be writing any sort of schematron rule (or whatever is analogous in this context) to make sure that `DistanceType = Radial Inner and Outer Boundary` is accompanied by `InnerBoundaryDistance` and `OuterBoundaryDistance`, and that `DistanceType = Radial Middle Boundary` is accompanied by `MiddleBoundaryDist` and `Width`?

**Comment by mit3ch** [comment]
@sarabond, This is really good; you've made great progress with organizing and presenting the ontology. As @matthewtiscareno  pointed out getting the details right will be a challenge and then keeping the contents current considering how much science is being done each year will be a problem. With no current outer planets missions, planetary ring parameters will be fairly stable. However, JWST can resolve rings out to Neptune, and there will be ongoing Earth based occultations of the various ring systems, especially for Uranus beginning in 2029.

**Comment by mit3ch** [comment]
I think you might consider ordering the fields under Solar System/Sun in order of increasing distance from the Sun. The complications to this would be the asteroids which don't confine themselves to the main belt, and the Centaurs (minor planets with orbits between Jupiter and Neptune). You could just show the latter after Neptune with an asterisk. Somehow, I'm just not expecting alphabetical order here.

**Comment by sarabond** [comment]
Hi @matthewtiscareno and @mit3ch , thank you both for your comments! I'll try and address them all here:

I was following the information that is listed at https://pds-rings.seti.org/saturn/saturn_rings_table.html for the Huygens Ringlet and other distance parameters, but I  understand them not being stable -- perhaps it's worth noting somewhere where it makes sense to do so that these are not stable numbers. Do the boundaries of all rings change,  or certain types only? Also -- is there another source you'd recommend for the parameters?

I can see the Cassini Division being a "subclass" intermediate group. If you have radial distances for the boundaries, I'll add that in.

Noted on the Alpha Ring. I'll make a note to delete that. 

I think I'm able to re-order the attributes but I'm not sure if it may matter for an ontology as much. 

As far as enforcing rules like schematron rules, I'm still investigating if this is something that can be done in an ontology -- I'll have to circle back on that.

As for the JWST and ongoing occultations, it sounds like keeping things up-to-date is a never-ending task, which is what I'd expect I think! 

I'm not sure if order is something that can be enforced -- but like with enforcing rules, I'll look into it.

Thank you again!

**Comment by jordanpadams** [comment]
Calling this iteration done for now. Future iterations to come in the next build cycle
